# Hash Set 
In this notebook I validate unique hashes for the datasets.

In [1]:
import mt_util as mt
import pandas as pd
import math
import hashlib
import shutil
# Helpful Functions
def getHWdim(size):
    x = int(math.sqrt(size))
    return x 
def getFileType(x):
    ss = x.split('.')
    return ss[len(ss) - 2]
def hashFile(path):
    return hashlib.md5(open(path,'rb').read()).hexdigest()
# Importing Image class from PIL module 
from PIL import Image 
import pathlib
def resizeIM(im_path, save_path, file_name):
    try:
        # Opens a image in RGB mode
        im = Image.open(im_path)
        newsize = (150, 150)
        im1 = im.resize(newsize)
        file_name = str(file_name) + '.png'
        save_path = save_path + "\\" + pathlib.PureWindowsPath(file_name).name
        im1.save(save_path)
    except Exception as e:
        print(e)

## Validate Exe Data

In [7]:
#data folder contains generated exe files
path = "data"
# Create the pandas DataFrame from object dictionary
df = pd.DataFrame([o.__dict__ for o in mt.get_files(path)])

# print dataframe.
df.head(5)

                          path    size           file_name file_ext
0  data\bin\AadmgbUMvO3065.exe  146376  AadmgbUMvO3065.exe     .exe
1  data\bin\AAMNKcCxxY2739.exe  146987  AAMNKcCxxY2739.exe     .exe
2  data\bin\aaOvJFGdFu1992.exe  147299  aaOvJFGdFu1992.exe     .exe
3  data\bin\AaTtYKSjfz1552.exe  146182  AaTtYKSjfz1552.exe     .exe
4  data\bin\aAXdlbSJrw2581.exe  146285  aAXdlbSJrw2581.exe     .exe

In [8]:
df

                                 path    size           file_name file_ext
0         data\bin\AadmgbUMvO3065.exe  146376  AadmgbUMvO3065.exe     .exe
1         data\bin\AAMNKcCxxY2739.exe  146987  AAMNKcCxxY2739.exe     .exe
2         data\bin\aaOvJFGdFu1992.exe  147299  aaOvJFGdFu1992.exe     .exe
3         data\bin\AaTtYKSjfz1552.exe  146182  AaTtYKSjfz1552.exe     .exe
4         data\bin\aAXdlbSJrw2581.exe  146285  aAXdlbSJrw2581.exe     .exe
...                               ...     ...                 ...      ...
9995  data\upx_bin\ZzSXQHrYdl3616.exe   85461  ZzSXQHrYdl3616.exe     .exe
9996  data\upx_bin\ZztnlYYvgU3313.exe   85697  ZztnlYYvgU3313.exe     .exe
9997  data\upx_bin\zzVGBDJlxt4742.exe   85492  zzVGBDJlxt4742.exe     .exe
9998  data\upx_bin\ZZYGXkGduk1168.exe   85265  ZZYGXkGduk1168.exe     .exe
9999  data\upx_bin\ZZZYDvARCE1563.exe   85668  ZZZYDvARCE1563.exe     .exe

[10000 rows x 4 columns]

In [9]:
df['dim'] = df['size'].apply(lambda x: getHWdim(x))
df['md5'] = df['path'].apply(lambda x: hashFile(x))
df

,path,size,file_name,file_ext,dim,md5
0,data\bin\AadmgbUMvO3065.exe,146376,AadmgbUMvO3065.exe,.exe,382,163440b3186e8d02cbf7def450c2f584
1,data\bin\AAMNKcCxxY2739.exe,146987,AAMNKcCxxY2739.exe,.exe,383,d3d7a7a3211a6ebe061710ee0240bd07
2,data\bin\aaOvJFGdFu1992.exe,147299,aaOvJFGdFu1992.exe,.exe,383,083645684c946dc55bd3a23f177c21ca
3,data\bin\AaTtYKSjfz1552.exe,146182,AaTtYKSjfz1552.exe,.exe,382,92dce75270ef17bd5f5f052d04700071
4,data\bin\aAXdlbSJrw2581.exe,146285,aAXdlbSJrw2581.exe,.exe,382,dead9fa281cce0d660eb18f397f4c7b4
...,...,...,...,...,...,...
9995,data\upx_bin\ZzSXQHrYdl3616.exe,85461,ZzSXQHrYdl3616.exe,.exe,292,699fa9a9e416acde5e507ed599fad6f2
9996,data\upx_bin\ZztnlYYvgU3313.exe,85697,ZztnlYYvgU3313.exe,.exe,292,27f6de8fc199b7d8d2238e4a321035d7
9997,data\upx_bin\zzVGBDJlxt4742.exe,85492,zzVGBDJlxt4742.exe,.exe,292,c416bf0b50537fd443e108b71ddf7c3f
9998,data\upx_bin\ZZYGXkGduk1168.exe,85265,ZZYGXkGduk1168.exe,.exe,292,2aa6e950e347b4807c2a54fa22cd93d0
9999,data\upx_bin\ZZZYDvARCE1563.exe,85668,ZZZYDvARCE1563.exe,.exe,292,cfaa3e7e41d2af753cf6a055d5db6576

In [10]:
df.md5.value_counts().mean()

1.0

In [11]:
mf = df.md5.value_counts().to_frame()
mf

                                  md5
163440b3186e8d02cbf7def450c2f584    1
142c96f90cfcc1dca4c914d4d406fb6c    1
ce9cb9e61a53cbe404412bd3090c64ad    1
ba22012e2ed96355fe401a0bc0e9556a    1
970ff1b4ced50faba7ab35f11eba2ba6    1
...                               ...
8833f2f37c7343da8144aaf934e8ee19    1
fa7e93ab60348bf9cff45ab39dc72dfa    1
59bd94aafe6142872615dc1cca98e6c9    1
2b1d7beca3d8ff505efa1746f8aadec1    1
cfaa3e7e41d2af753cf6a055d5db6576    1

[10000 rows x 1 columns]

In [12]:
mf.query("md5 == 1")

                                  md5
163440b3186e8d02cbf7def450c2f584    1
142c96f90cfcc1dca4c914d4d406fb6c    1
ce9cb9e61a53cbe404412bd3090c64ad    1
ba22012e2ed96355fe401a0bc0e9556a    1
970ff1b4ced50faba7ab35f11eba2ba6    1
...                               ...
8833f2f37c7343da8144aaf934e8ee19    1
fa7e93ab60348bf9cff45ab39dc72dfa    1
59bd94aafe6142872615dc1cca98e6c9    1
2b1d7beca3d8ff505efa1746f8aadec1    1
cfaa3e7e41d2af753cf6a055d5db6576    1

[10000 rows x 1 columns]

In [13]:
df.to_csv("combined_exes.csv")
mf.to_csv("combined_exes_hashes.csv")

## Validate Image Data
In this section I read in the image file data generated by the mt_util script. This image files have been stored in two directories: ubin for uncompressed exe files and cbin for compressed exe files that were imaged.

In [2]:
#data folder contains generated exe files
path = "img_data"
# Create the pandas DataFrame from object dictionary
df = pd.DataFrame([o.__dict__ for o in mt.get_files(path)])

# print dataframe.
df.head(5)

,path,size,file_name,file_ext
0,img_data\cbins\test\AadmgbUMvO3065.exe.png,48934,AadmgbUMvO3065.exe.png,.png
1,img_data\cbins\test\AAMNKcCxxY2739.exe.png,49155,AAMNKcCxxY2739.exe.png,.png
2,img_data\cbins\test\aaOvJFGdFu1992.exe.png,49416,aaOvJFGdFu1992.exe.png,.png
3,img_data\cbins\test\AaTtYKSjfz1552.exe.png,49240,AaTtYKSjfz1552.exe.png,.png
4,img_data\cbins\test\aAXdlbSJrw2581.exe.png,49042,aAXdlbSJrw2581.exe.png,.png

In [3]:
df['dim'] = df['size'].apply(lambda x: getHWdim(x))
df['md5'] = df['path'].apply(lambda x: hashFile(x))
df

,path,size,file_name,file_ext,dim,md5
0,img_data\cbins\test\AadmgbUMvO3065.exe.png,48934,AadmgbUMvO3065.exe.png,.png,221,dffed2b1524daad6345d6601aa40e67f
1,img_data\cbins\test\AAMNKcCxxY2739.exe.png,49155,AAMNKcCxxY2739.exe.png,.png,221,cd1d94cc17fbf78364209e591e177e8e
2,img_data\cbins\test\aaOvJFGdFu1992.exe.png,49416,aaOvJFGdFu1992.exe.png,.png,222,9bdfbb0e2bc290f390bb73d9751ea30a
3,img_data\cbins\test\AaTtYKSjfz1552.exe.png,49240,AaTtYKSjfz1552.exe.png,.png,221,d22e3e2963003724e6568f8c52063b6e
4,img_data\cbins\test\aAXdlbSJrw2581.exe.png,49042,aAXdlbSJrw2581.exe.png,.png,221,3298417e6aff0ba5f57e564bfd21138a
...,...,...,...,...,...,...
9995,img_data\ubins\validation\ZzSXQHrYdl3616.exe.png,58471,ZzSXQHrYdl3616.exe.png,.png,241,0491b0c8331c5bf9631f928a9845709f
9996,img_data\ubins\validation\ZztnlYYvgU3313.exe.png,59139,ZztnlYYvgU3313.exe.png,.png,243,c19e4746b0679fcef05a88f23be6c530
9997,img_data\ubins\validation\zzVGBDJlxt4742.exe.png,58376,zzVGBDJlxt4742.exe.png,.png,241,6e6d9c0ce647c160f2b6d9b03a089c12
9998,img_data\ubins\validation\ZZYGXkGduk1168.exe.png,58434,ZZYGXkGduk1168.exe.png,.png,241,d27266b3055beaf98c2f269483a1141f
9999,img_data\ubins\validation\ZZZYDvARCE1563.exe.png,58445,ZZZYDvARCE1563.exe.png,.png,241,877d446f06b59c2ab635def4b596e7fe

<div class="alert alert-block alert-info">
<b>Hash Validation:</b> Now that the all the files in the data frame have been hashed, I create a seperate dataframe to store the hashes simply to do a small query to verify there is only 1 hash per file. I verify that the total rows in this query output match in each dataframe.
</div>

In [4]:
df.md5.value_counts().mean()

1.0

In [5]:
mf = df.md5.value_counts().to_frame()
mf

                                  md5
dffed2b1524daad6345d6601aa40e67f    1
e46222ab2800d05263cf3f657607a4c8    1
72afa5386c6319c4310dc0e32e0eee9a    1
c74ea0da29ba90a67ef3025cc651917b    1
8f8f6e3e807a4caf647b7e4427052ad4    1
...                               ...
88409a6ae92e320bbcbf9f6ec1ca3a96    1
4969cf194e655de4dc4fe6d6b9806c10    1
e4e6a401b448c60780680148af7fc7e8    1
3fea48d9673dfbb5cc8d71c1828822e2    1
877d446f06b59c2ab635def4b596e7fe    1

[10000 rows x 1 columns]

In [6]:
mf.query("md5 == 1")

                                  md5
dffed2b1524daad6345d6601aa40e67f    1
e46222ab2800d05263cf3f657607a4c8    1
72afa5386c6319c4310dc0e32e0eee9a    1
c74ea0da29ba90a67ef3025cc651917b    1
8f8f6e3e807a4caf647b7e4427052ad4    1
...                               ...
88409a6ae92e320bbcbf9f6ec1ca3a96    1
4969cf194e655de4dc4fe6d6b9806c10    1
e4e6a401b448c60780680148af7fc7e8    1
3fea48d9673dfbb5cc8d71c1828822e2    1
877d446f06b59c2ab635def4b596e7fe    1

[10000 rows x 1 columns]

In [7]:
df.to_csv("combined_png.csv")
mf.to_csv("combined_png_hashes.csv")

## Verify All Files
In this section I combine all folders into a single directory to perform the same steps. This final step should render 20K unique files.

In [8]:
#data folder contains generated exe files
path = "cdata"
# Create the pandas DataFrame from object dictionary
df = pd.DataFrame([o.__dict__ for o in mt.get_files(path)])

# print dataframe.
df.head(5)

                                path    size           file_name file_ext
0  cdata\data\bin\AadmgbUMvO3065.exe  146376  AadmgbUMvO3065.exe     .exe
1  cdata\data\bin\AAMNKcCxxY2739.exe  146987  AAMNKcCxxY2739.exe     .exe
2  cdata\data\bin\aaOvJFGdFu1992.exe  147299  aaOvJFGdFu1992.exe     .exe
3  cdata\data\bin\AaTtYKSjfz1552.exe  146182  AaTtYKSjfz1552.exe     .exe
4  cdata\data\bin\aAXdlbSJrw2581.exe  146285  aAXdlbSJrw2581.exe     .exe

In [9]:
df['dim'] = df['size'].apply(lambda x: getHWdim(x))
df['md5'] = df['path'].apply(lambda x: hashFile(x))
df

,path,size,file_name,file_ext,dim,md5
0,cdata\data\bin\AadmgbUMvO3065.exe,146376,AadmgbUMvO3065.exe,.exe,382,163440b3186e8d02cbf7def450c2f584
1,cdata\data\bin\AAMNKcCxxY2739.exe,146987,AAMNKcCxxY2739.exe,.exe,383,d3d7a7a3211a6ebe061710ee0240bd07
2,cdata\data\bin\aaOvJFGdFu1992.exe,147299,aaOvJFGdFu1992.exe,.exe,383,083645684c946dc55bd3a23f177c21ca
3,cdata\data\bin\AaTtYKSjfz1552.exe,146182,AaTtYKSjfz1552.exe,.exe,382,92dce75270ef17bd5f5f052d04700071
4,cdata\data\bin\aAXdlbSJrw2581.exe,146285,aAXdlbSJrw2581.exe,.exe,382,dead9fa281cce0d660eb18f397f4c7b4
...,...,...,...,...,...,...
19995,cdata\img_data\ubins\validation\ZzSXQHrYdl3616...,58471,ZzSXQHrYdl3616.exe.png,.png,241,0491b0c8331c5bf9631f928a9845709f
19996,cdata\img_data\ubins\validation\ZztnlYYvgU3313...,59139,ZztnlYYvgU3313.exe.png,.png,243,c19e4746b0679fcef05a88f23be6c530
19997,cdata\img_data\ubins\validation\zzVGBDJlxt4742...,58376,zzVGBDJlxt4742.exe.png,.png,241,6e6d9c0ce647c160f2b6d9b03a089c12
19998,cdata\img_data\ubins\validation\ZZYGXkGduk1168...,58434,ZZYGXkGduk1168.exe.png,.png,241,d27266b3055beaf98c2f269483a1141f
19999,cdata\img_data\ubins\validation\ZZZYDvARCE1563...,58445,ZZZYDvARCE1563.exe.png,.png,241,877d446f06b59c2ab635def4b596e7fe

In [10]:
df.md5.value_counts().mean()

1.0

In [11]:
mf = df.md5.value_counts().to_frame()
mf

                                  md5
163440b3186e8d02cbf7def450c2f584    1
37cad4e87fc020b0883e743ca28f01cb    1
3e86cc0b5e189e38957d5f57c16e32be    1
3fea48d9673dfbb5cc8d71c1828822e2    1
e4e6a401b448c60780680148af7fc7e8    1
...                               ...
5b8555a5a84e07c5e54fb0c93e96f2ed    1
970ff1b4ced50faba7ab35f11eba2ba6    1
ba22012e2ed96355fe401a0bc0e9556a    1
ce9cb9e61a53cbe404412bd3090c64ad    1
877d446f06b59c2ab635def4b596e7fe    1

[20000 rows x 1 columns]

In [12]:
mf.query("md5 == 1")

                                  md5
163440b3186e8d02cbf7def450c2f584    1
37cad4e87fc020b0883e743ca28f01cb    1
3e86cc0b5e189e38957d5f57c16e32be    1
3fea48d9673dfbb5cc8d71c1828822e2    1
e4e6a401b448c60780680148af7fc7e8    1
...                               ...
5b8555a5a84e07c5e54fb0c93e96f2ed    1
970ff1b4ced50faba7ab35f11eba2ba6    1
ba22012e2ed96355fe401a0bc0e9556a    1
ce9cb9e61a53cbe404412bd3090c64ad    1
877d446f06b59c2ab635def4b596e7fe    1

[20000 rows x 1 columns]

<div class="alert alert-block alert-info">
<b>Success!!:</b> This notebook shows 20K unique files for training.
</div>